### ISSUE TITLE
Get Exception when no results

### ISSUE THREAD

**Issue by hqin2013** [JustRaviga/laravel-pexels#2]
Hi,
Thank you for supplying this package. 
search "heartbeat dog toys", maybe getting no results will cause a null exception.

- Laravel Model Related Fields Version: #.#.#
- PHP Version: 8.0.11
- Laravel/Lumen Framework Version:9.25.1
- Database Driver & Version:

### Description:
$client = Pexels::photos();

$response = $client->search('heartbeat dog toys');

### Execution result:
JustRaviga\Pexels\Entities\PhotosSearchResponse::__construct(): Argument #1 ($totalResults) must be of type int, null given

**Comment by DeDmytro** [comment]
Thank you for interest to the package, @hqin2013 !
I suppose everything good with your request because the the Pexels itself return results you were looking for. https://www.pexels.com/search/heartbeat%20dog%20toys/

I think this error is related to hourly api quota. I'll wrap that into more meaningful exception.

**Comment by DeDmytro** [comment]
The issue was related to incorrect Authorization header. Fixed in: https://github.com/JustRaviga/laravel-pexels/commit/bb3c2564e1545624a4afb192b3313614ccc88111
